# Generated by Django 4.2.5 on 2023-09-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0002_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainservice',
            name='cost',
            field=models.IntegerField(),
        ),
    ]
