# Generated by Django 4.2.5 on 2023-09-18 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0003_alter_domainservice_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceservice',
            name='serviced_processed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insurance_processed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='licenseservice',
            name='serviced_processed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='license_processed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sslcertificateservice',
            name='serviced_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ssl_certificate_processed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
