# Generated by Django 4.2.5 on 2023-09-19 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0003_subscription'),
        ('Services', '0005_rename_serviced_processed_by_insuranceservice_processed_by_and_more'),
    ]

    operations = [
    ]
