# Generated by Django 4.2.4 on 2023-09-26 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0007_alter_insuranceservice_total_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceservice',
            name='insurance_type',
            field=models.CharField(choices=[('Medical Insurance', 'Medical Insurance'), ('Car Insurance', 'Car Insurance'), ('Building Insurance', 'Building Insurance')], max_length=100),
        ),
    ]
