# Generated by Django 4.2.4 on 2023-09-26 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0008_alter_insuranceservice_insurance_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='contract',
            field=models.FileField(blank=True, null=True, upload_to='contracts/'),
        ),
        migrations.AlterField(
            model_name='insuranceservice',
            name='insurance_type',
            field=models.CharField(max_length=100),
        ),
    ]
