# Generated by Django 4.2.4 on 2023-09-26 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0009_serviceprovider_contract_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenseservice',
            name='license',
            field=models.FileField(blank=True, null=True, upload_to='licences/'),
        ),
    ]
