# Generated by Django 4.2.5 on 2023-09-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0010_licenseservice_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='contract',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
