# Generated by Django 4.2.5 on 2023-09-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0010_licenseservice_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='dial_codes',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
