# Generated by Django 4.2.4 on 2023-09-29 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0011_alter_serviceprovider_contract'),
        ('Services', '0011_client_dial_codes'),
    ]

    operations = [
    ]
