# Generated by Django 4.2.4 on 2023-10-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0012_merge_20230929_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='dial_codes',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='service_offered',
            field=models.CharField(choices=[('Domain', 'Domain'), ('Insurance', 'Insurance'), ('Licenses', 'Licenses'), ('SSL Certificates', 'SSL Certificates')], max_length=100),
        ),
    ]
