# Generated by Django 4.2.4 on 2023-10-03 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0012_merge_20230929_1009'),
        ('Services', '0013_serviceprovider_dial_codes_and_more'),
    ]

    operations = [
    ]
