# Generated by Django 4.2.5 on 2023-10-04 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0014_merge_20231003_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovider',
            name='dial_codes',
        ),
    ]
