# Generated by Django 4.2.5 on 2023-10-04 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0015_remove_serviceprovider_dial_codes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='dial_codes',
        ),
    ]
