# Generated by Django 4.2.5 on 2023-10-11 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0015_insuranceservice_total_cost_currency_and_more'),
        ('Services', '0016_remove_client_dial_codes'),
    ]

    operations = [
    ]
