# Generated by Django 4.2.5 on 2023-10-12 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0017_merge_20231010_0936'),
        ('Services', '0017_merge_20231011_0755'),
    ]

    operations = [
    ]
