# Generated by Django 4.2.5 on 2023-10-12 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0018_merge_20231012_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenseservice',
            name='license_type',
            field=models.CharField(blank=True, choices=[('Trading License', 'Trading License'), ('System License', 'System License'), ('Labor License', 'Labor License')], max_length=20, null=True),
        ),
    ]
