# Generated by Django 4.2.5 on 2023-10-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0019_licenseservice_license_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ein',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='rfi_document',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='tin',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
