# Generated by Django 4.2.5 on 2023-10-12 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0020_customuser_ein_serviceprovider_rfi_document_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceprovider',
            old_name='rfi_document',
            new_name='rfidoc',
        ),
    ]
