# Generated by Django 4.2.4 on 2024-04-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0022_alter_customuser_ein_alter_customuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=200)),
                ('date_of_birth', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=10)),
                ('contact', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='domainservice',
            name='client',
        ),
        migrations.RemoveField(
            model_name='domainservice',
            name='service_provider',
        ),
        migrations.RemoveField(
            model_name='insuranceservice',
            name='processed_by',
        ),
        migrations.RemoveField(
            model_name='insuranceservice',
            name='service_provider',
        ),
        migrations.RemoveField(
            model_name='licenseservice',
            name='processed_by',
        ),
        migrations.RemoveField(
            model_name='licenseservice',
            name='service_provider',
        ),
        migrations.RemoveField(
            model_name='sslcertificateservice',
            name='service_provider',
        ),
        migrations.RemoveField(
            model_name='sslcertificateservice',
            name='serviced_by',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='provider',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='DomainService',
        ),
        migrations.DeleteModel(
            name='InsuranceService',
        ),
        migrations.DeleteModel(
            name='LicenseService',
        ),
        migrations.DeleteModel(
            name='ServiceProvider',
        ),
        migrations.DeleteModel(
            name='SSLCertificateService',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
