# Generated by Django 4.2.4 on 2024-05-30 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0024_remove_customuser_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='gender',
        ),
        migrations.AddField(
            model_name='farmer',
            name='farm_size',
            field=models.IntegerField(default=20),
        ),
    ]
