# Generated by Django 4.2.4 on 2024-05-30 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0025_remove_farmer_contact_remove_farmer_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmer',
            old_name='name',
            new_name='user_name',
        ),
    ]
