# Generated by Django 4.2.4 on 2024-05-30 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0026_rename_name_farmer_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmer',
            old_name='user_name',
            new_name='username',
        ),
    ]
