# Generated by Django 4.2.4 on 2024-05-31 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0028_rename_location_farmer_farmlocation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='password',
        ),
    ]
