# Generated by Django 4.2.4 on 2024-05-31 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0029_remove_farmer_created_at_remove_farmer_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='contact',
            field=models.CharField(max_length=20),
        ),
    ]
