# Generated by Django 4.2.4 on 2024-06-06 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0030_alter_farmer_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='severity_level',
            field=models.CharField(default='low', max_length=100),
        ),
    ]
