# Generated by Django 4.2.4 on 2024-06-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0031_farmer_severity_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='admin_role',
            field=models.CharField(choices=[('admin', 'Admin'), ('agricultural expert', 'Agricultural expert')], default='admin', max_length=19),
        ),
    ]
