# Generated by Django 4.2.4 on 2024-06-10 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0032_alter_customuser_admin_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmer',
            old_name='severity_level',
            new_name='severity',
        ),
    ]
